Feature/wonder
OOP-Team-11/RoadsAndBoats pull request #22
Opened 2017-04-14 03:21 UTC by anipmehta

2017-04-14 14:00 UTC, gavinscheele requested changes

2017-04-14 14:00 UTC, gdscheele commented on src/main/game/model/PlayerId.java
> +    public PlayerId(int num){
this shouldn't be here

2017-04-14 14:00 UTC, gdscheele commented on src/main/game/model/wonder/Wonder.java
> +    Vector<Vector<WonderBrick>> wonderbricks;
can you make this private

2017-04-14 14:00 UTC, gdscheele commented on src/main/game/model/wonder/WonderManager.java
> +
This still needs to be implemented

2017-04-14 14:00 UTC, gdscheele commented on src/main/game/model/wonder/Wonder.java
> +        if(!flag){
can you rename the flag variable to be more descriptive

2017-04-14 14:00 UTC, gdscheele commented on src/main/game/model/wonder/Wonder.java
>  }
We still need a method getWealthPoints(PlayerId) which will return the total wealth points that a player earned in the wonder. This needs to account for the number of bricks each player has in each row.

2017-04-14 19:13 UTC, anipmehta commented on src/main/game/model/wonder/Wonder.java
> +    Vector<Vector<WonderBrick>> wonderbricks;
@gdscheele Just to make sure you are talking about the wonderbicks right??

2017-04-14 19:18 UTC, gdscheele commented on src/main/game/model/wonder/Wonder.java
> +    Vector<Vector<WonderBrick>> wonderbricks;
yeah

2017-04-14 23:21 UTC, anipmehta commented
@gdscheele Only turnDesertToPasture is left else every review were implemented.

2017-04-14 23:22 UTC, anipmehta commented on src/main/game/model/wonder/Wonder.java
> +        if(!flag){
Done

2017-04-14 23:22 UTC, anipmehta commented on src/main/game/model/wonder/Wonder.java
>  }
Added

2017-04-15 02:42 UTC, anipmehta commented
Added more test in Wonder stuff as suggested by @gdscheele .

2017-04-15 17:41 UTC, anipmehta commented
@gdscheele I have implemented turnDesertToPasture functionality. Please review if that is a correct way or do I need to change anything.

2017-04-15 21:20 UTC, anipmehta commented
@Juan-Jauregui Updated turnDesertToPasture functionality.

2017-04-17 00:43 UTC, anipmehta commented
Wonder Functionality is almost complete. Pls review.
@tonny-12 All tests passed.

2017-04-17 02:03 UTC, gavinscheele submitted a review, later dismissed

2017-04-17 02:03 UTC, tonny-12 approved these changes

2017-04-17 02:07 UTC, merged